# Generated by Django 2.2 on 2019-04-22 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='state',
            field=models.IntegerField(choices=[(1, 'Todo'), (2, 'In-Progress'), (3, 'Done')], default=1),
        ),
    ]
